### ISSUE TITLE
Missing index name

### ISSUE THREAD

**Issue by wilke** [MG-RAST/pipeline#546]
https://github.com/MG-RAST/pipeline/blob/fdf24ec9ef800a4c3726a6301b65918a380c24ff/CWL/Workflows/rna-annotation.workflow.cwl#L53

This should be a string not a directory object - missing index name in workflow input?

**Comment by teharrison** [comment]
bad copy-paste, it had the same object as above, instead of what it
needed.  sending fix.

**Comment by teharrison** [comment]
fixed with pull request #547
