### ISSUE TITLE
Missing file superblat

### ISSUE THREAD

**Issue by TheBestUser** [MG-RAST/pipeline#577]
https://github.com/MG-RAST/pipeline/blob/1ffd23171114307a17738625b388294300269d2a/Dockerfile#L154

Step 25/26 : COPY superblat /usr/local/bin/
lstat superblat: no such file or directory

**Comment by TheBestUser** [comment]
Where can I find this file?
Of course, if possible. Thanks!

**Comment by wgerlach** [comment]
Sorry for the delay, is fixed.
